---
language: python
python: "2.7"

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

install:
  # - pip install --upgrade pytest
  - pip install ansible
  - pip install molecule
  - pip install docker-py

script:
  - molecule test
