---
language: python
python: "2.7"

sudo: required

services:
  - docker

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible
  - pip install molecule
  - pip install docker-py

script:
  - molecule --debug test
