---
language: python
python: "2.7"

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update -qq

install:
  - pip install molecule
  - pip install docker-py

script:
  - molecule test
