---
- name: Converge
  hosts: all
  become: true
  roles:
    - role: ansiblebit.oracle-java
      oracle_java_use_defaults: false
      oracle_java_apt_repository: 'deb http://ppa.launchpad.net/webupd8team/java/ubuntu bionic main'
      oracle_java_apt_repository_key: '7B2C3B0889BF5709A105D03AC2518248EEA14886'
      oracle_java_cache_valid_time: 3600
      oracle_java_deb_package: 'oracle-java8-installer'
      oracle_java_debconf_package_default: 'oracle-java8-set-default'
      oracle_java_home: "/usr/lib/jvm/java-8-oracle"
      oracle_java_license_version: "shared/accepted-oracle-license-v1-1"
      oracle_java_set_as_default: false
      oracle_java_state: latest
    - role: fluteansible
  tasks:
    - name: mkdir for score
      file:
        dest: /var/opt/flute/score
        state: directory
        mode: "0775"
        group: flute

    - name: copy flute config file
      copy:
        src: flute.xml
        dest: /opt/flute/flute.xml
        mode: "0644"

    - name: start flute service
      service:
        name: flute
        state: started
      when: ansible_connection != 'docker'
